# Generated by Django 5.0.14 on 2026-09-02 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='Code2', help_text='Lucide React icon name', max_length=50)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='Code2', help_text='Lucide React icon name', max_length=50)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.JSONField(default=list, help_text="List of tags (e.g. ['Android', 'iOS'])")),
                ('items', models.JSONField(default=list, help_text="List of sub-items (e.g. ['Corporate Sites', 'E-Commerce'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
