# Generated by Django 5.2.17 on 2026-09-16 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_service_testimonial_websitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(help_text='e.g. Founder & CEO', max_length=200)),
                ('bio', models.TextField(help_text='Short professional bio')),
                ('photo_url', models.URLField(help_text='URL to profile photo', max_length=500)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader Profile',
                'verbose_name_plural': 'Leader Profiles',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
