# Generated by Django 5.2.17 on 2026-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaderprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload profile photo', upload_to='leaders/'),
        ),
    ]
