# Generated by Django 5.2.17 on 2026-09-16 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_leaderprofile_photo_url_leaderprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. Education, Healthcare, Finance', max_length=150)),
                ('desc', models.TextField(help_text='Description of the solution')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enterprise Solution',
                'verbose_name_plural': 'Enterprise Solutions',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
